import{i as a,S as l}from"./assets/vendor-beb23274.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const u=()=>{const t=document.createElement("span");t.classList.add("loader"),document.body.append(t)},c=()=>{const t=document.querySelector(".loader");t&&t.remove()};document.querySelector(".form").addEventListener("submit",function(t){t.preventDefault();const o=document.querySelector("input").value.trim();if(!o){a.error({title:"Error",message:"Please enter a valid search term"});return}u();const n=`https://pixabay.com/api/?key=42337135-3774c2f446ec3f71c1b4c916a&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;fetch(n).then(e=>e.json()).then(e=>p(e)).catch(e=>{console.error("Error fetching data:",e),c(),a.error({title:"Error",message:"An error occurred while fetching data. Please try again later."})})});function p(t){c();const o=document.querySelector(".gallery");if(o.innerHTML="",t.hits.length===0){a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"center",transitionIn:"fadeInLeft"});return}const i=new l(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}),n=t.hits.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <p><b>Likes: </b>${e.likes}</p>
            <p><b>Views: </b>${e.views}</p>
            <p><b>Comments: </b>${e.comments}</p>
            <p><b>Downloads: </b>${e.downloads}</p>
        </li>`).join("");o.insertAdjacentHTML("beforeend",n),i.on("show.simplelightbox").refresh()}
//# sourceMappingURL=commonHelpers.js.map
