import{i as a,S as l}from"./assets/vendor-beb23274.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const p=document.querySelector("input"),u=document.querySelector(".form"),d=()=>{const r=document.createElement("span");r.classList.add("loader"),document.body.append(r)},c=()=>{const r=document.querySelector(".loader");r&&r.remove()};u.addEventListener("submit",async function(r){r.preventDefault();const o=p.value.trim();if(!o){a.error({title:"Error",message:"Please enter a valid search term"});return}d();const s={apiKey:"42337135-3774c2f446ec3f71c1b4c916a",baseUrl:"https://pixabay.com/api/"},n=`https://pixabay.com/api/?key=${s==null?void 0:s.apiKey}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`;try{const e=await fetch(n);if(!e.ok)throw new Error("Network response was not ok");const t=await e.json();m(t)}catch(e){console.error("Error fetching data:",e),c(),a.error({title:"Error",message:"An error occurred while fetching data. Please try again later.",position:"center"})}});function m(r){const o=document.querySelector(".gallery");o.innerHTML="";const s=new l(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}),n=r.hits.map(e=>`
        <li class="gallery-item">
            <a href="${e.largeImageURL}">
                <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <p><b>Likes: </b>${e.likes}</p>
            <p><b>Views: </b>${e.views}</p>
            <p><b>Comments: </b>${e.comments}</p>
            <p><b>Downloads: </b>${e.downloads}</p>
        </li>`).join("");o.innerHTML=n,s.refresh(),c()}
//# sourceMappingURL=commonHelpers.js.map
